#!/usr/bin/env bash
# Configure new nginx server to have a custom header
spt-get -y update
apt-get install -y nginx
sed -i '11i\add_header X-served-By $HOSTNAME;' /etc/nginx/nginx.conf
service nginx restart
