#!/usr/bin/env bash
# Configure new nginx server to have a custom header
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i '11i\\\add_header X-served-By $HOSTNAME;' /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
